# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Ensure you have the necessary certificates and provisioning profiles configured in your project

    increment_build_number # Optional: Automatically increment the build number

    gym(
      scheme: "Runner", # Replace with your app's scheme
      export_method: "app-store",
      export_options: {
        uploadBitcode: false,
        compileBitcode: true,
        uploadSymbols: true,
        stripSwiftSymbols: true,
        export_xcargs: "-allowProvisioningUpdates",
        output_name: "ReleaseApp.ipa"
      }
    )

    pilot(
      distribute_external: false, # Set to true if you want to distribute outside your team
      changelog: "Version 1.0" # Provide release notes/changelog
    )
  end
end

