
default_platform(:android)

lane :bump_version_code do
  path = '../app/build.gradle'
  re = /versionCode\s+(\d+)/ 
  s = File.read(path)
  versionCode = s[re, 1].to_i
  s[re, 1] = (versionCode + 1).to_s
  f = File.new(path, 'w')
  f.write(s)
  f.close
end

lane :deploy_internal_testers_release do |options|
  gradle(task: 'assemble', build_type: 'Release')
  upload_to_play_store(
    package_name:options[:package_name]||'com.carparts.app',
    track: 'internal', 
    release_status: 'draft',
    skip_upload_changelogs: true,
    aab: "../build/app/outputs/bundle/release/app-release.aab"
  )
  end

  # lane :deploy_production_release do |options|
  # gradle(task: 'assemble', build_type: 'Release')
  # upload_to_play_store(
  #   track: 'production',
  #   package_name:options[:package_name]||'com.carparts.app', 
  #   skip_upload_changelogs: true,
  #   aab: "../build/app/outputs/bundle/release/app-release.aab"
  # )
  # end